name = "osrs-bank-viewer"
compatibility_date = "2026-04-28"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "BANK_KV"
id = "ec9058b898b14e31b73f64979271b272"

[vars]
BANK_PLAYER = "funmaxxing"
STATS_PLAYER = "funmaxxing"
